# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
pygments: true
markdown: kramdown


defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: 李某某

description: Stylish Jekyll Theme
author:
  name: Light
  email: light-li@hotmail.com
  github: lichunqiang
  twitter: chunqiang.lee
  pinterest: light
  linkedin: light
  bio: I can do better!
  email_md5: 44d97c8966000a5ea9a1140cdb688e4a

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html
lab_path: lab.html

BASE_PATH:
